/*
 * Generated by ISE 18.07.10.1981 GPL Edition - unix
 */

#include "eif_eiffel.h"
#include "eif_project.h"
#include "egc_include.h"

#ifdef __cplusplus
extern "C" {
#endif
extern void F1_23();
extern EIF_REFERENCE F1_14();
extern void F230_6501();
extern void F232_6675();
extern void F237_6744();
extern void F238_6883();
extern void F297_3801();
extern void F256_6382();
extern void F113_1598();
extern EIF_REFERENCE F113_1585();
extern EIF_BOOLEAN F113_1597();
extern EIF_BOOLEAN F113_1605();
extern void F113_1607();
extern void F113_1608();
extern void F113_1609();
extern void F46_1128();
extern EIF_TYPED_VALUE F46_1129();

long *eif_area_table = (long *)0;
long *eif_lower_table = (long *)0;


extern void egc_init_plug (void); 
void egc_init_plug (void)
{
	egc_prof_enabled = (EIF_INTEGER) 0;
	egc_correct_mismatch = (void (*)(EIF_REFERENCE)) F1_23;
	egc_twin = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F1_14;
	egc_strmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F230_6501;
	egc_str32make = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F237_6744;
	egc_arrmake = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F297_3801;
	egc_strset = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F232_6675;
	egc_str32set = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F238_6883;
	egc_routdisp_wb = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F256_6382;
	egc_is_scoop_capable = 1;
	egc_set_exception_data = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F113_1598;
	egc_set_last_exception = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F113_1597;
	egc_last_exception = (EIF_TYPED_VALUE (*)(EIF_REFERENCE)) F113_1585;
	egc_is_code_ignored = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F113_1605;
	egc_once_raise = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F113_1607;
	egc_init_exception_manager = (void (*)(EIF_REFERENCE)) F113_1608;
	egc_free_preallocated_trace = (void (*)(EIF_REFERENCE)) F113_1609;

	egc_str_dtype = 231;

	egc_str32_dtype = 237;
	egc_arr_dtype = 296;
	egc_tup_dtype = 185;
	egc_disp_rout_id = 3209;
	egc_copy_rout_id = 18;
	egc_is_equal_rout_id = 11;

	egc_sp_char = 0x033B;
	egc_sp_wchar = 0x0352;
	egc_sp_bool = 0x0227;
	egc_sp_uint8 = 0x01A1;
	egc_sp_uint16 = 0x0262;
	egc_sp_uint32 = 0x01D9;
	egc_sp_uint64 = 0x02F1;
	egc_sp_int8 = 0x02A9;
	egc_sp_int16 = 0x02CD;
	egc_sp_int32 = 0x0239;
	egc_sp_int64 = 0x0316;
	egc_sp_real32 = 0x017D;
	egc_sp_real64 = 0x0285;
	egc_sp_pointer = 0x014C;
	egc_sp_ref = 0x0126;

	egc_uint8_dtype = 205;
	egc_uint16_dtype = 214;
	egc_uint32_dtype = 211;
	egc_uint64_dtype = 223;
	egc_int8_dtype = 187;
	egc_int16_dtype = 220;
	egc_int32_dtype = 217;
	egc_int64_dtype = 196;
	egc_bool_dtype = 199;
	egc_real32_dtype = 208;
	egc_char_dtype = 193;
	egc_wchar_dtype = 190;
	egc_real64_dtype = 202;
	egc_point_dtype = 226;

	egc_exception_dtype = 62;
	egc_except_emnger_dtype = 112;

	egc_ce_type = egc_ce_type_init;

	egc_ce_exp_type = egc_ce_exp_type_init;
	egc_fsystem = egc_fsystem_init;
	egc_system_mod_init = egc_system_mod_init_init;
	egc_partab = egc_partab_init;
	egc_partab_size = egc_partab_size_init;
	egc_foption = egc_foption_init;
	egc_frozen = egc_frozen_init;
	egc_fpatidtab = egc_fpatidtab_init;
	egc_address_table = egc_address_table_init;
	egc_fpattern = egc_fpattern_init;

	egc_einit = egc_einit_init;
	egc_tabinit = egc_tabinit_init;
	egc_forg_table = egc_forg_table_init;

	egc_system_name = "application";
	egc_system_location = "/home/shivashish/Desktop/CS17BTECH11037_P2/EIFGENs/application/W_code";
	egc_compiler_tag = 38;
	egc_project_version = 1541734295;
	egc_has_old_special_semantic = 0;
	egc_has_ieee_semantic = 1;
	scount = 959;

	egc_rcount = 1;
	egc_ridx = 0;
	egc_rlist = (char**) eif_malloc (sizeof(char*)*egc_rcount);
	egc_rcdt = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcrid = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rcarg = (int32 *) eif_malloc (sizeof(int32)*egc_rcount);
	egc_rlist[0] = "APPLICATION.make";
	egc_rcdt[0] = 0;
	egc_rcrid[0] = 4943;
	egc_rcarg[0] = 0;
	
	
	egc_platform_level = 0x00000D00;
	egc_rt_extension_dt = 45;
	egc_rt_extension_notify = (void (*)(EIF_REFERENCE, EIF_TYPED_VALUE, EIF_TYPED_VALUE)) F46_1128;
	egc_rt_extension_notify_argument = (EIF_TYPED_VALUE (*)(EIF_REFERENCE, EIF_TYPED_VALUE)) F46_1129;
}

void egc_rcdt_init (void)
{
	if (egc_rcdt[0] == 0) {
		egc_rcdt[0] = 957; /* APPLICATION */
	}
}

#ifdef __cplusplus
}
#endif
